### ISSUE TITLE
[Feature]: カード (横)

### ISSUE THREAD

**Issue by wiyco** [iputapp/lounas#41]
# Tasks (Features)

TEAM PIPLUP

@duke-imo

## Overview of Tasks (Features)

タスクの概要

`カード (横)`のコンポーネント

- `ランキング`
- `あなたへのおすすめ`

![image](https://github.com/wiyco/imap/assets/72733890/66d3dede-09f0-4511-972b-6039c1524795)

## Todo

想定される作業

- [x] コンポーネント名は `CardHorizontal` にする。
- [x] コンポーネントは `src/components/cards/` に置く。
- [x] 画像は`<img>`タグを使わず、[`Next.js` の `<Image>`](https://nextjs.org/docs/app/api-reference/components/image) を使う。(パフォーマンス向上のため)
- [x] 右端の青色(数字)は `src/styles/_variables.scss` に定義されている `$blue` (`#07f`) を使う。
- [x] 右端の数字のフォントは @Shvain に相談。

## Before submitting

> **Warning**
>
> 以下はチェックのみ編集を許可する。(内容の追加および変更は禁じる)

- [x] [行動規範(Code of Conduct)](https://github.com/wiyco/imap/blob/develop/_docs/CODE_OF_CONDUCT.md)に同意します。

## Remark

補足事項を記入してください。
